In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [17]:
import numpy as np

# 5.1 Introduction to pandas Data Structures

### Series

In [3]:
obj = pd.Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

And so on...

In [5]:
obj.values

array([ 4,  7, -5,  3])

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

create a Series with an index identifying each data point with a label:

In [8]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [9]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2['a']

-5

In [12]:
obj2['d'] = 6

In [13]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [14]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [15]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [18]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [19]:
'b' in obj2

True

In [20]:
'e' in obj2

False

**create a Series from data in a dictionary by passing in the dict:**

In [23]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [25]:
obj3 = pd.Series(sdata)

In [26]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

When passing a dict, the index in the resulting Series will have the dict's keys in sorted order. You can override this by passing the dict keys in the order you want them to appear in the resulting Series:

In [27]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [28]:
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

isnull and notnull functions in pandas should be used to detect missing data:

In [29]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [31]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

A useful Series feature for many applications is that it automatically aligns by index label in arithmetic operations:

In [32]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [33]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [34]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [35]:
obj4.name = 'population'

In [36]:
obj4.index.name = 'state'

In [37]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

A Series's index can be altered in-place by assignment:

In [38]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [39]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [40]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

Common way to construct a DataFrame is from a dict of equal-length lists or NumPy arrays:

In [41]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

The resulting DataFrame will have its index assigned automatically as with Series , and the columns are placed in sorted order:

In [42]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [43]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

If you specify a sequence of columns, the DataFrame's columns will be arranged in that order:

In [44]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

If you pass a column that isn't contained in the dict, it will appear with missing values in the result:

In [45]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [46]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [47]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [48]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

Rows can also be retrieved by position or name with the special loc attribute

In [49]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

Columns can be modified by assignment. 

In [50]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [57]:
frame2['debt'] = np.arange(6.)

In [58]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

When assigning lists or arrays to a column, the value's length must match the length of the Data Frame. If you assign a Series, its labels will be realigned exactly to the DataFrame's index, inserting missing values in any holes:

In [59]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [60]:
frame2['debt'] = val

In [61]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

add new column state = ohio boolean

In [62]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

delete new column using del

In [63]:
del frame2['eastern']

In [64]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

Nested Dict of Dicts:

In [65]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

If the nexted dict is passed to the DataFrame, pandas will interpret the outer dict keys as the columns and the inner keys as the row indices:

In [66]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

transpose DataFrame (swap rows and columns)

In [67]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [68]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN


Dicts of Series

In [69]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

DataFrame's index and columns set name

In [70]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [71]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [72]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### Index Objects

In [73]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [74]:
index = obj.index

In [75]:
index

Index(['a', 'b', 'c'], dtype='object')

In [76]:
index[1:]

Index(['b', 'c'], dtype='object')

In [ ]:
index[1] = 'd' # TypeError

In [77]:
labels = pd.Index(np.arange(3))

In [78]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [79]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [80]:
obj2.index is labels

True

In addition to being array-like, an Index also behaves like a fixed-size set:

In [81]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [82]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [83]:
'Ohio' in frame3.columns

True

In [84]:
2003 in frame3.index

False

Unlike Python sets, a pandas Index can contain duplicate labels:

In [85]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

# 5.2 Essential Functionality

### Reindexing

reindex means create a new object with the data conformed to a new index

In [86]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

calling reindex on this series rearranges the data according to the new index, introducting missing values if any index values were not already present:

In [87]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

for ordered data like time series, it may be desireable to do some interpolation or filling of values when reindexing. The method option allows us to do this, using a method such as ffill, which forward-fills the values:

In [88]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

obj3

0      blue
2    purple
4    yellow
dtype: object

In [89]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

reindex can alter either the row(index), columns, or both:

In [90]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index=['a', 'c', 'd'],
                    columns=['Ohio', 'Texas', 'California'])

In [91]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [92]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

reindexed with columns keyword:

In [93]:
states = ['Texas', 'Utah', 'California']

In [94]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

you can reindex more succinctly by label-indexing with loc:

In [96]:
frame.loc[['a', 'b', 'c', 'd'], states]

KeyError: "['Utah'] not in index"

### Dropping Entries from an Axis

drop method will return a new object with the indicated value(s) deleted from an axis:

In [97]:
obj = pd. Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [98]:
new_obj = obj.drop('c')

new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

with DataFrame, index values can be deleted from either axis:

In [99]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [100]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

can drop values from the columns by passing axis=1 or axis='columns':

In [101]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [102]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

drop can modify an object in-place without returning a new object

#### be careful with the inplace as it destroys any data that is dropped

In [103]:
obj.drop('c', inplace=True)

In [104]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

## Indexing, Selection, and Filtering

Series indexing (obj[...]) works analogously to NumPy array indexing, except you can use the Series's index values instead of only integers

In [105]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [106]:
obj['b']

1.0

In [107]:
obj[1]

1.0

In [108]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [109]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [110]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [111]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

Slicing with labels behaves differently than normal Python slicing in that the end point is inclusive:

In [112]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

Setting using these methods modifies the corresponding section of the Series:

In [113]:
obj['b':'c'] = 5

obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

indexing into a dataFrame is for retrieving one or more columns either with a single value or sequence:

In [114]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [115]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [116]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [117]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [118]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [119]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [120]:
data[data < 5] = 0

data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Selection with loc and iloc

enable you to select a subset of the rows and columns from a DataFrame using either axis lables (loc) or integers (iloc)

select a single row and multiple columns by lable:

In [121]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

similar selections using iloc:

In [122]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [123]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [124]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

both indexing functions work with slices in addition to single labels or lists of labels:

In [125]:
data.loc[: 'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [126]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

## Integer Indexes

working with pandas objects indexed by integers:

this throws error:  

ser = pd.Series(np.arange(3.))  
ser  
ser[-1]  

pandas could "fall back" on integer indexing, but inferring what the user wants (label-based or position-based imdexing)is difficult.

In [128]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

with non-integer index, there is no potential for ambiguity:

In [129]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [130]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [131]:
ser.iloc[:1]

0    0.0
dtype: float64

## Arithmetic and Data Alignment

behavior of arithmetic between objects with different indexes. when you are adding together objects, if any index. pairs are not the same, the respective index in the result will be the union of the index pairs.

In [132]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [133]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [134]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [135]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [136]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

in the case of DataFrame, alignment is performed on both rows and columns:


In [137]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                  index=['Ohio', 'Texas', 'Colorado'])

In [143]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), 
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [139]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [144]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [145]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

rows and columns that are NOT found on both DataFrame objects will appear empty

if you add DataFrame objects with no column or row labels in common, the result will contain all nulls:

In [146]:
df1 = pd.DataFrame({'A': [1, 2]})

In [147]:
df2 = pd.DataFrame({'B': [3, 4]})

In [148]:
df1

A
0  1
1  2

In [149]:
df2

B
0  3
1  4

In [150]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

### Arithmetic methods with fill values

in arithmetic operations between differently indexed objects, you might want to fill with a special value, like 0 when an axis label is found in one object but not the other:

In [151]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))

In [152]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

In [153]:
df2.loc[1, 'b'] = np.nan

In [154]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [155]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [156]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

using the add method on df1, pass df2 and an argument to fill_value:

In [157]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [158]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [159]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [160]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### Operations between DataFrame and Series

arithmetic between DataFrame and Series. difference between a two-dimensional array and one of its rows:

In [161]:
arr = np.arange(12.).reshape((3, 4))

arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [162]:
arr[0]

array([0., 1., 2., 3.])

In [163]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

when we subtract arr[0] from arr, the subraction is performed once for each row. this is referred to as **broadcasting**

In [164]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [165]:
series = frame.iloc[0]

In [166]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [167]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [168]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

**If an index value is not found in either the DataFrame's columns or the Series's index, the objects will be reindexed to form the union:**

In [169]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [170]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

if you want to instead broadcast over the columns, matching on the rows, you have to use one of the arithmetic methods:

In [171]:
series3 = frame['d']

In [172]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [173]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [174]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

**The axis number that you pass is the axis to match on. In this case we mean to match on the DataFrame's row index (axis= 'index' or axis=0) and broadcast accross

## Function Application and Mapping

NumPy ufuncs(element-wise array methods) also work with pandas objects:

In [176]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [177]:
frame

b         d         e
Utah   -1.593648 -0.061484 -0.915970
Ohio    1.191687 -0.934419  0.496361
Texas   1.169618 -0.594781  0.108872
Oregon -1.153955  1.776485  0.638370

In [178]:
np.abs(frame)

b         d         e
Utah    1.593648  0.061484  0.915970
Ohio    1.191687  0.934419  0.496361
Texas   1.169618  0.594781  0.108872
Oregon  1.153955  1.776485  0.638370

applying a function on one-dimensional arrays to each column or row. DataFrame's apply method:

In [181]:
f = lambda x: x.max() - x.min()

In [182]:
frame.apply(f)

b    2.785335
d    2.710905
e    1.554340
dtype: float64

In [183]:
frame.apply(f, axis='columns')

Utah      1.532163
Ohio      2.126106
Texas     1.764400
Oregon    2.930441
dtype: float64

In [184]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [185]:
frame.apply(f)

b         d        e
min -1.593648 -0.934419 -0.91597
max  1.191687  1.776485  0.63837

In [186]:
format = lambda x: '%.2f' % x

In [187]:
frame.applymap(format)

b      d      e
Utah    -1.59  -0.06  -0.92
Ohio     1.19  -0.93   0.50
Texas    1.17  -0.59   0.11
Oregon  -1.15   1.78   0.64

In [188]:
frame['e'].map(format)

Utah      -0.92
Ohio       0.50
Texas      0.11
Oregon     0.64
Name: e, dtype: object

### Sorting and Ranking

to sort lexicographically by row or column index, use the sort_index method, which returns a new, sorted object:

In [189]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [190]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [198]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                    index=['three', 'one'],
                    columns=['d', 'a', 'b', 'c'])

In [199]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [200]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [202]:
#can be sorted in descending

frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

**sort series by values use sort_values method**

In [203]:
obj = pd.Series([4, 7, -3, 2])

In [204]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

any missing values are sorted to the end of the Series by default:

In [205]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [207]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

when sorting a DataFrame, you can use the data in one or more columns as the sort keys. To do so, pass one or more column names to the by option of sort_values

In [208]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [209]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

**sort by multiple columns, pass a list of names:**

In [210]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

Ranking assigns ranks from one through the number of valid data points in an array.

In [211]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [212]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [213]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [214]:
#Assign tie values the maximum rank in the group

obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

DataFrame can compute ranks over the rows or the columns:

In [215]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0,1,0,1],
                     'c': [-2, 5, 8, -2.5]})

In [216]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [217]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### Axis Indexes with Duplicate Labels

In [218]:
obj = pd.Series(range(5), index =['a', 'a', 'b', 'b', 'c'])

obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

the index's is_unique property can tell you whether its labels are unique or not

In [219]:
obj.index.is_unique

False

In [220]:
obj['a']

a    0
a    1
dtype: int64

In [222]:
obj['c']

4

In [223]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

df

0         1         2
a  0.415953 -0.261213  0.863987
a -0.900838 -0.539606  0.139195
b -1.075918  0.345928 -0.034263
b -0.869099 -0.396808 -0.403458

In [224]:
df.loc['b']

0         1         2
b -1.075918  0.345928 -0.034263
b -0.869099 -0.396808 -0.403458

## 5.3 Summarizing and Computing Descriptive Statistics

In [225]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
                 index=['a', 'b', 'c', 'd'], columns=['one', 'two'])

df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [226]:
df.sum() #returns a Series containing column sums:

one    9.25
two   -5.80
dtype: float64

passing axis='columns' or axis=1 sums across the columns instead:

In [227]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

NA values are excluded unless the entire slice (row or column) is NA. This can be disabled with the skipna option:

In [228]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

some methods like idxmin and idxmax return indirect statistics like the index value wher ethe minimum or maximum values are attained:

In [229]:
df.idxmax()

one    b
two    d
dtype: object

In [230]:
df.cumsum() #accumulations

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

multiple summary statistics in one shot

In [231]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

on non-numeric data, describe produces alternative summary statistics:

In [232]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [233]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

## Correlation and Covariance

In [237]:
import sys
!{sys.executable} -m pip install pandas_datareader


  Using cached pandas_datareader-0.10.0-py3-none-any.whl (109 kB)
  Using cached lxml-4.9.1.tar.gz (3.4 MB)
  Preparing metadata (setup.py) ... done
  Created wheel for lxml: filename=lxml-4.9.1-cp310-cp310-macosx_12_0_arm64.whl size=1492404 sha256=1ac10007c29437220af29158a904afeb0ac470944358d9f7e53192dd54380951
  Stored in directory: /Users/kendra/Library/Caches/pip/wheels/a4/ec/7b/8acde6da24b5aabeee049213d5bec12d1e9214d3cae276387b
Successfully built lxml
You should consider upgrading via the '/opt/homebrew/Cellar/jupyterlab/3.4.3/libexec/bin/python3.10 -m pip install --upgrade pip' command.


In [238]:
import pandas_datareader.data as web

In [239]:
all_data = {ticker: web.get_data_yahoo(ticker)
           for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})

volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [240]:
returns = price.pct_change()

In [241]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2022-07-19  0.026722 -0.052487  0.020767  0.042853
2022-07-20  0.013510 -0.012989  0.010558  0.000698
2022-07-21  0.015094 -0.015714  0.009799  0.002964
2022-07-22 -0.008111  0.008651 -0.016916 -0.058067
2022-07-25 -0.007398  0.002261 -0.005876 -0.001384

the corr method of Series computes the correlation of the overlapping, non-NA, aligned-by-index values in two Series. RElatedly, cov computes the covariance:

In [242]:
returns['MSFT'].corr(returns['IBM'])

0.4778851831692941

In [243]:
returns['MSFT'].cov(returns['IBM'])

0.00015208163880356304

In [245]:
returns.MSFT.corr(returns.IBM)

0.4778851831692941

In [246]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.432526  0.757195  0.682658
IBM   0.432526  1.000000  0.477885  0.444723
MSFT  0.757195  0.477885  1.000000  0.784277
GOOG  0.682658  0.444723  0.784277  1.000000

In [247]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000410  0.000150  0.000285  0.000256
IBM   0.000150  0.000294  0.000152  0.000141
MSFT  0.000285  0.000152  0.000345  0.000270
GOOG  0.000256  0.000141  0.000270  0.000344

using corrwith method, you can compute pairwise correlations between a DataFrame's columns or rows with another Series or DataFrame.

In [248]:
returns.corrwith(returns.IBM)

AAPL    0.432526
IBM     1.000000
MSFT    0.477885
GOOG    0.444723
dtype: float64

In [249]:
returns.corrwith(volume)

AAPL   -0.075818
IBM    -0.113844
MSFT   -0.072830
GOOG   -0.085597
dtype: float64

## Unique Values, Value Counts, and Membership

In [250]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [251]:
uniques = obj.unique()

In [252]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [253]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [254]:
pd.value_counts(obj.values, sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [255]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [257]:
mask = obj.isin(['b', 'c'])

mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

related to isin is the Index.get_indexer method, which gives you an index array from an array of possibly non-distinct values into another array of distinct values

In [258]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [259]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [260]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In some cases, you may want to compute a histogram on multiple related columns in a DataFrame

In [261]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                    'Qu2': [2, 3, 1, 2, 3],
                    'Qu3': [1, 5, 2, 4, 4]})


In [262]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [263]:
result = data.apply(pd.value_counts).fillna(0)

result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0